-- 0063_manufacturer_price — the manufacturer's own figure, and the uplift that
-- turned it into the line's price.
--
-- Ops receives a price per line from the manufacturer and has to reach a
-- customer price from it. Before this the only way in was to do the margin
-- arithmetic by hand and type the finished number into 0046's override, which
-- keeps the answer and loses the question: nothing recorded what they quoted or
-- what was added to it.
--
--   manufacturer_price      their figure, ALWAYS ex-GST. An inc-GST entry is
--                           divided by 1.1 and rounded to cents before it is
--                           stored, so one column never holds two bases
--                           (src/data/manufacturerPrice.ts is the one place
--                           that conversion lives).
--   manufacturer_uplift_pct the percentage applied to it, per line. Not a
--                           project setting and not a global: a line that
--                           explains itself later needs the number that was
--                           actually used, not a lookup against a default that
--                           has since moved (grill D1).
--
-- line_total stays THE price — every downstream sum already reads it, exactly
-- as 0046 reasoned. This pair is the WORKING, not a second answer.
--
-- NULL manufacturer_price means the line was not priced this way. That is the
-- whole test: one nullable column carrying the state, never a boolean beside
-- the figures that can disagree with them — 0046's rule, and the owner's
-- ruling that a price is a price, so no new price state exists anywhere.
--
-- Attribution is NOT duplicated. price_override_by / price_override_at (0046)
-- record who and when for both price paths; one place per fact.
--
-- children affected: none. ALTER TABLE ADD COLUMN touches no rows, so no
-- cascade can fire. For the record, quote_line's children are its own
-- parent_line_id (ON DELETE CASCADE, 0028) plus ON DELETE SET NULL references
-- from file (0003), the schedule tables (0012) and the opening/learning tables
-- (0022, 0047) — none of which this migration goes near.
ALTER TABLE quote_line ADD COLUMN manufacturer_price     REAL;
ALTER TABLE quote_line ADD COLUMN manufacturer_uplift_pct REAL;
